- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 36000 # 10 h
    - !type:RoleTimeRequirement # DeltaV - JobDetective time requirement. Give them an understanding of basic forensics.
      role: JobHeadOfPersonnel
      time: 3600
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hours
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: CaptainGear
  equipment:
    #shoes: ClothingShoesBootsLaceup - DeltaV - Commented out for loadout options
    eyes: ClothingEyesGlassesSunglasses
    #gloves: ClothingHandsGlovesCaptain - DeltaV - Commented out for loadout options
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
