- type: gameMapPool
  id: DefaultMapPool
  maps:
# DeltaV
  - Arena
  - Asterisk
  - Edge
  - Hammurabi
  - Lighthouse
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  - Submarine
# Offs
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  #- Train <- return after station anchoring PR is finished and merged

# Corvax
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxPilgrim
