- type: job
  id: Borgjan
  name: "борг уборщик"
  setPreference: false
  description: job-description-borg
  playTimeTracker: JobBorgjan
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 999999
  canBeAntag: false
  icon: JobIconBorgJanitor
  supervisors: job-supervisors-rd
  startingGear: RobotGear # for char preview only
