- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hours
  canBeAntag: false
  icon: JobIconBorg
  setPreference: false
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
  startingGear: RobotGear # for char preview only

- type: startingGear
  id: RobotGear
  equipment:
    head: ClothingHeadHatCardborg
    outerClothing: ClothingOuterCardborg
