- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-chief-headquarters-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - CentralCommandOfficial
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom

- type: startingGear
  id: CentCommOfficialEVAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelHoldingCentCommOfficial
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTCentcomm
    mask: ClothingMaskGasCentcom
    id: OffCCPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponModefiedDisabler
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
    suitstorage: AirTankFilled
    neck: ClothingNeckCloakCentcom
    head: ClothingHeadHatCentcom
