- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      - Shuttle
      - Singularity
      - SolarPanels
      - Artifacts
      - Zoo
      - MiningOutpost
      - Tesla
