- type: job
  id: Judge
  name: job-name-judge
  description: job-description-judge
  playTimeTracker: JobJudge
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Justice
      time: 10800
  startingGear: JudgeGear
  icon: "JobIconJudge"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Command
  - External
  - Lawyer
  - Security
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: JudgeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    neck: ClothingNeckLawyerbadge
  inhand:
    - BriefcaseIAAFilled
